BTC:
  URL: 
  KEYPAIR:
    - ADDRESS: 
      PRIKEY: 
ETH: 
  URL: 
  KEYPAIR:
    - ADDRESS:
      PRIKEY: 

LTC:
  URL: 
  KEYPAIR:
    - ADDRESS: 
      PRIKEY:

ATOM:
  URL:
  KEYPAIR:
    - ADDRESS:
      PRIKEY:

DOT:
  URL: 
  KEYPAIR:
    - ADDRESS: 
      PRIKEY: 