BTC:
  URL: 
  KEYPAIR:
    - ADDRESS: 
      PRIKEY: 
    - ADDRESS: 
      PRIKEY: 
ETH: 
  URL:
  USDT: "0x0093b27dA6a4A611f31e5c00A89897E874132E66"
  USDC: "0x56dc763551F106c9EA80CCA0521f7a7Bca79eC9E"
  KEYPAIR:
    - ADDRESS:
      PRIKEY: 

LTC:
  URL: 
  KEYPAIR:
    - ADDRESS: 
      PRIKEY:

ATOM:
  URL:
  KEYPAIR:
    - ADDRESS:
      PRIKEY:

DOT:
  URL: 
  KEYPAIR:
    - ADDRESS: 
      PRIKEY: 